# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Ifconfig-Wrapper
version:      0.10
version_from: lib/Net/Ifconfig/Wrapper.pm
installdirs:  site
requires:
    POSIX:                         0
    Win32::API:                    0
    Win32::WinError:               0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
